export { generate, generate as generateInterior, type GenerateOptions } from './placements/generate.js';
export { presentModels } from './assets/availability.js';
export { INTERIOR_RECIPES, interiorRecipe } from './architecture/recipes.js';
export { writePlacements } from './placements/write.js';
export { buildModules } from './modules/index.js';
export { makeFixture, type FixtureOptions } from './blueprint/fixture.js';
export * from './nav.js';
export { coreFeasibility, type CoreFeasibility } from './layout/index.js';
export { InteriorError } from './core/errors.js';
export type * from './placements/types.js';
export type * from './core/types.js';
export { expandBuilding } from './placements/expand.js';
export { makePlacementFixture } from './blueprint/placement-fixture.js';
